<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-24 19:24
=======
# Generated by Django 5.2 on 2025-04-24 20:53
>>>>>>> 7d4df57f1553477c09ec40459ea519bb2cfd116d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('serie', models.CharField(max_length=50)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
=======
            name='FormularioMarcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoas_moram', models.CharField(max_length=50)),
                ('casa', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
                ('escolaridade_pai', models.CharField(max_length=50)),
                ('escolaridade_mae', models.CharField(max_length=50)),
                ('renda_familiar', models.CharField(max_length=50)),
                ('renda_mensal', models.CharField(max_length=50)),
                ('trabalha', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField()),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], max_length=10)),
                ('score_vulnerabilidade', models.IntegerField(default=0)),
>>>>>>> 7d4df57f1553477c09ec40459ea519bb2cfd116d
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
