# Generated by Django 5.2 on 2025-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_entrevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
