# Generated by Django 5.2 on 2025-04-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_perfil_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('serie', models.CharField(max_length=50)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
