# Generated by Django 5.2 on 2025-05-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_aluno_data_entrevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=50, verbose_name='Curso escolhido'),
        ),
    ]
