# Generated by Django 5.2 on 2025-05-06 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_curso_aluno_score_alter_aluno_data_entrevista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='serie',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meu_app.curso', verbose_name='Curso escolhido'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='preferencia_turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Preferência de Entrevista'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
