# Generated by Django 5.2 on 2025-05-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0006_remove_aluno_serie_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariomarcacao',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meu_app.curso'),
        ),
        migrations.AddField(
            model_name='formulariomarcacao',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, null=True),
        ),
    ]
