# Generated by Django 5.2 on 2025-05-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0008_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meu_app.curso', verbose_name='Curso desejado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencia_turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Preferência de Turno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='preferencia_turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Preferência de Entrevista'),
        ),
        migrations.AlterField(
            model_name='formulariomarcacao',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10, null=True),
        ),
    ]
