# Generated by Django 5.2 on 2025-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0009_perfil_curso_perfil_preferencia_turno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='preferencia_turno',
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=6, verbose_name='Turno'),
        ),
    ]
