# Generated by Django 5.2 on 2025-05-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0010_remove_perfil_preferencia_turno_curso_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='motivo_rejeicao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('E', 'Selecionado para entrevista'), ('R', 'Não selecionado')], default='P', max_length=1),
        ),
    ]
